// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cache.sql

package store

import (
	"context"
	"time"
)

const deleteExpired = `-- name: DeleteExpired :one
WITH geocoding AS (
    DELETE FROM geocoding_cache WHERE geocoding_cache.expires_at <= $1 RETURNING 1
), weather AS (
    DELETE FROM weather_cache WHERE weather_cache.expires_at <= $1 RETURNING 1
)
SELECT (SELECT count(*) FROM geocoding) AS geocoding_deleted, (SELECT count(*) FROM weather) AS weather_deleted
`

type DeleteExpiredRow struct {
	GeocodingDeleted int64
	WeatherDeleted   int64
}

func (q *Queries) DeleteExpired(ctx context.Context, now time.Time) (DeleteExpiredRow, error) {
	row := q.db.QueryRow(ctx, deleteExpired, now)
	var i DeleteExpiredRow
	err := row.Scan(&i.GeocodingDeleted, &i.WeatherDeleted)
	return i, err
}

const getGeocoding = `-- name: GetGeocoding :one
SELECT found, location_id, name, admin1, country, latitude, longitude
FROM geocoding_cache
WHERE query = $1 AND expires_at > $2
`

type GetGeocodingParams struct {
	Query string
	Now   time.Time
}

type GetGeocodingRow struct {
	Found      bool
	LocationID *int64
	Name       *string
	Admin1     *string
	Country    *string
	Latitude   *float64
	Longitude  *float64
}

func (q *Queries) GetGeocoding(ctx context.Context, arg GetGeocodingParams) (GetGeocodingRow, error) {
	row := q.db.QueryRow(ctx, getGeocoding, arg.Query, arg.Now)
	var i GetGeocodingRow
	err := row.Scan(
		&i.Found,
		&i.LocationID,
		&i.Name,
		&i.Admin1,
		&i.Country,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const getWeather = `-- name: GetWeather :one
SELECT temperature_c, apparent_temperature_c, relative_humidity_pct, wind_speed_kmh, weather_code
FROM weather_cache
WHERE location_id = $1 AND expires_at > $2
`

type GetWeatherParams struct {
	LocationID int64
	Now        time.Time
}

type GetWeatherRow struct {
	TemperatureC         float64
	ApparentTemperatureC float64
	RelativeHumidityPct  float64
	WindSpeedKmh         float64
	WeatherCode          int32
}

func (q *Queries) GetWeather(ctx context.Context, arg GetWeatherParams) (GetWeatherRow, error) {
	row := q.db.QueryRow(ctx, getWeather, arg.LocationID, arg.Now)
	var i GetWeatherRow
	err := row.Scan(
		&i.TemperatureC,
		&i.ApparentTemperatureC,
		&i.RelativeHumidityPct,
		&i.WindSpeedKmh,
		&i.WeatherCode,
	)
	return i, err
}

const upsertGeocoding = `-- name: UpsertGeocoding :exec
INSERT INTO geocoding_cache (query, found, location_id, name, admin1, country, latitude, longitude, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (query) DO UPDATE SET
    found       = excluded.found,
    location_id = excluded.location_id,
    name        = excluded.name,
    admin1      = excluded.admin1,
    country     = excluded.country,
    latitude    = excluded.latitude,
    longitude   = excluded.longitude,
    expires_at  = excluded.expires_at
`

type UpsertGeocodingParams struct {
	Query      string
	Found      bool
	LocationID *int64
	Name       *string
	Admin1     *string
	Country    *string
	Latitude   *float64
	Longitude  *float64
	ExpiresAt  time.Time
}

func (q *Queries) UpsertGeocoding(ctx context.Context, arg UpsertGeocodingParams) error {
	_, err := q.db.Exec(ctx, upsertGeocoding,
		arg.Query,
		arg.Found,
		arg.LocationID,
		arg.Name,
		arg.Admin1,
		arg.Country,
		arg.Latitude,
		arg.Longitude,
		arg.ExpiresAt,
	)
	return err
}

const upsertWeather = `-- name: UpsertWeather :exec
INSERT INTO weather_cache (
    location_id, temperature_c, apparent_temperature_c, relative_humidity_pct, wind_speed_kmh, weather_code, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (location_id) DO UPDATE SET
    temperature_c          = excluded.temperature_c,
    apparent_temperature_c = excluded.apparent_temperature_c,
    relative_humidity_pct  = excluded.relative_humidity_pct,
    wind_speed_kmh         = excluded.wind_speed_kmh,
    weather_code           = excluded.weather_code,
    expires_at             = excluded.expires_at
`

type UpsertWeatherParams struct {
	LocationID           int64
	TemperatureC         float64
	ApparentTemperatureC float64
	RelativeHumidityPct  float64
	WindSpeedKmh         float64
	WeatherCode          int32
	ExpiresAt            time.Time
}

func (q *Queries) UpsertWeather(ctx context.Context, arg UpsertWeatherParams) error {
	_, err := q.db.Exec(ctx, upsertWeather,
		arg.LocationID,
		arg.TemperatureC,
		arg.ApparentTemperatureC,
		arg.RelativeHumidityPct,
		arg.WindSpeedKmh,
		arg.WeatherCode,
		arg.ExpiresAt,
	)
	return err
}
