// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"
)

type GeocodingCache struct {
	Query      string
	Found      bool
	LocationID *int64
	Name       *string
	Admin1     *string
	Country    *string
	Latitude   *float64
	Longitude  *float64
	ExpiresAt  time.Time
}

type WeatherCache struct {
	LocationID           int64
	TemperatureC         float64
	ApparentTemperatureC float64
	RelativeHumidityPct  float64
	WindSpeedKmh         float64
	WeatherCode          int32
	ExpiresAt            time.Time
}
